<?php
echo "soal 1" . "\n";
$angka1 = 5; $angka2 = 4;
$hasil = $angka1 + $angka2; 
echo "hasil penjumlahan : " . $hasil = $angka1 + $angka2 ."\n"; 
$hasil = $angka1 - $angka2;
echo "hasil pengurangan : " . $hasil = $angka1 - $angka2 . "\n";
$hasil = $angka1 * $angka2;
echo "hasil perkalian : " . $hasil = $angka1 * $angka2 . "\n";
$hasil = $angka1 / $angka2;
echo "hasil pembagian : " . $hasil = $angka1 / $angka2 . "\n";
$hasil = $angka1 % $angka2;
echo "sisa pembagian 5 dibagi 4 : " . $hasil = $angka1 % $angka2 ."\n";
echo "soal 2" . "\n";
$x = 10;
echo "$x ditambah 5 : "  . $x += 5;
echo"\n";
$x = 10;
echo "$x dikurangi 2 : " . $x -= 2;
echo "\n";
echo "soal 3" . "\n";
$nilai1 =90; $nilai2 = 95;
$hasil_besar = $nilai1 > $nilai2;
echo "apakah $nilai1 lebih besar dari $nilai2? " . ($hasil_besar? "ya" : "tidak") . "\n";
$sama_dengan = $nilai1 == $nilai2;
echo "apakah $nilai1 sama dengan $nilai2? " . ($sama_dengan? "ya" : "tidak") ."\n";
echo "soal 4" . "\n";
$benar = true ; $salah = false;
$benar && $salah;
echo $benar && $salah;
$benar || $salah;
echo $benar || $salah;
echo "\n";
echo "soal 5" . "\n";
$hitung = 5;
$hitung++;
echo "nilai increment : " . $hitung++ . "\n";
$hitung = 5;
$hitung--;
echo "nilai decrement : " . $hitung-- . "\n";
echo "soal 6" . "\n";
$nama_depan = "yosefin"; $nama_belakang = "kurniawati";
echo "nama saya adalah " . $nama_depan . $nama_belakang . "\n";
echo "soal 7" . "\n";
$a = 5; $b = 5;
$rata_rata = ($a + $b) / 2;
echo "nilai rata-rata dari variabel $a dan $b : " . $rata_rata  . "\n";
$x = 5;
$lebih_besar = $rata_rata > $x;
echo "apakah nilai rata-rata lebih besar dari 5? " . ($lebih_besar? "ya" : "tidak");